/**
 * Build pipeline:
 *   1. cargo build the Rust kernels for wasm32-unknown-unknown
 *   2. copy the .wasm into dist/
 *   3. emit dist/spectrum.js  (classic script, defines global `Spectrum`;
 *                              drop-in for the original spectrum.js)
 *      emit dist/spectrum.mjs (ES module exporting Spectrum and ready)
 *
 * The wasm is embedded as base64 so the drop-in is still a single file.
 *
 * Usage: deno run -A scripts/build.ts [--skip-cargo]
 */

import { encodeBase64 } from "@std/encoding/base64";
import { fromFileUrl } from "@std/path";

const root = fromFileUrl(new URL("../", import.meta.url));
const wasmCrate = `${root}wasm`;
const wasmOut = `${wasmCrate}/target/wasm32-unknown-unknown/release/spectrum_wasm.wasm`;
const dist = `${root}dist`;

/** Strip ES module syntax so sources can be concatenated into one scope. */
export function stripModuleSyntax(src: string): string {
  return src
    .split("\n")
    .filter((line) => !/^\s*\/\/\s*@ts-(check|nocheck)/.test(line))
    .filter((line) => !/^\s*import\s.*from\s/.test(line))
    .map((line) => line.replace(/^export\s+(?=(async\s+)?(function|class|const|let)\b)/, ""))
    .join("\n");
}

/** Indent every non-empty line by `n` spaces. */
function indent(src: string, n = 2): string {
  const pad = " ".repeat(n);
  return src.split("\n").map((l) => (l.length ? pad + l : l)).join("\n");
}

const HEADER = `/*!
 * spectrum-wasm — WebAssembly drop-in replacement for spectrum.js
 * Original spectrum.js Copyright (c) 2019 Jeppe Ledet-Pedersen, MIT license.
 * Generated by scripts/build.ts — do not edit.
 */`;

/** Shared bootstrap: instantiate the core, sync if allowed, else async. */
const BOOT = `
const ref = { core: null };
const Spectrum = defineSpectrum(ref, globalObj);
const wasmBytes = base64ToBytes(WASM_BASE64);
let ready;
try {
  ref.core = createSpectrumCore(wasmBytes);
  ready = Promise.resolve(Spectrum);
} catch (_syncError) {
  // Some engines forbid synchronous compilation on the main thread.
  ready = createSpectrumCoreAsync(wasmBytes).then((c) => {
    ref.core = c;
    return Spectrum;
  });
  ready.catch(() => {});
}
Object.defineProperties(Spectrum, {
  ready: { value: ready, enumerable: true },
  implementation: { value: "wasm", enumerable: true },
  version: { value: VERSION, enumerable: true },
  core: { get: () => ref.core, enumerable: true },
});
`;

export function renderClassic(
  core: string,
  spectrum: string,
  b64: string,
  version: string,
): string {
  const body = [
    stripModuleSyntax(core),
    stripModuleSyntax(spectrum),
    `const WASM_BASE64 = "${b64}";`,
    `const VERSION = ${JSON.stringify(version)};`,
    BOOT,
    `globalObj.Spectrum = Spectrum;`,
  ].join("\n");
  return `${HEADER}
(function (globalObj) {
  "use strict";
${indent(body)}
})(typeof globalThis !== "undefined" ? globalThis : this);
`;
}

export function renderModule(
  core: string,
  spectrum: string,
  b64: string,
  version: string,
): string {
  return `${HEADER}
const globalObj = globalThis;
${stripModuleSyntax(core)}
${stripModuleSyntax(spectrum)}
const WASM_BASE64 = "${b64}";
const VERSION = ${JSON.stringify(version)};
${BOOT}
export { Spectrum, ready, createSpectrumCore, createSpectrumCoreAsync, defineSpectrum };
export default Spectrum;
`;
}

async function cargoBuild() {
  const cmd = new Deno.Command("cargo", {
    args: ["build", "--release", "--target", "wasm32-unknown-unknown"],
    cwd: wasmCrate,
    stdout: "inherit",
    stderr: "inherit",
  });
  const { code } = await cmd.output();
  if (code !== 0) throw new Error(`cargo build failed (exit ${code})`);
}

async function cargoVersion(): Promise<string> {
  const toml = await Deno.readTextFile(`${wasmCrate}/Cargo.toml`);
  return toml.match(/^version\s*=\s*"([^"]+)"/m)?.[1] ?? "0.0.0";
}

if (import.meta.main) {
  if (!Deno.args.includes("--skip-cargo")) await cargoBuild();
  await Deno.mkdir(dist, { recursive: true });

  const wasm = await Deno.readFile(wasmOut);
  const b64 = encodeBase64(wasm);
  const core = await Deno.readTextFile(`${root}src/wasm_core.js`);
  const spectrum = await Deno.readTextFile(`${root}src/spectrum.js`);
  const version = await cargoVersion();

  await Deno.writeFile(`${dist}/spectrum_wasm.wasm`, wasm);
  await Deno.writeTextFile(`${dist}/spectrum.js`, renderClassic(core, spectrum, b64, version));
  await Deno.writeTextFile(`${dist}/spectrum.mjs`, renderModule(core, spectrum, b64, version));
  await Deno.copyFile(`${root}public/colormaps.js`, `${dist}/colormaps.js`);

  // deno-lint-ignore no-console
  console.log(
    `built dist/ — wasm ${wasm.byteLength} B, spectrum.js ${
      (await Deno.stat(`${dist}/spectrum.js`)).size
    } B`,
  );
}
